
### USUARIOS GERAIS
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "User",
    "senha": "1231111",
    "email": "user@mail.com"
}

###
POST http://localhost:3000/api/users/email
Content-Type: application/json

{
    "email": "user@mail.com"
}

###
GET http://localhost:3000/api/users/all




### PARTICIPANTES

POST http://localhost:3000/api/participante
Content-Type: application/json

{
    "username": "Legolas",
    "senha": "123",
    "email": "legolas@mail.com",
    "nomeCompleto": "Legolas Arqueiro",
    "cpf": "q11111",
    "endereco": {
        "logradouro": "Sésamo",
        "bairro": "Vila",
        "cidade": "Arroba",
        "uf": "SP",
        "cep": "123123",
        "numero": "22",
        "referencia": "Top"
    }
}

###
POST http://localhost:3000/api/participante/email
Content-Type: application/json

{
    "email": "joaozin@mail.com"
}

###
GET http://localhost:3000/api/participante/all